version: "3"
services:
  myapp:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: ${SERVICE_NAME}
    env_file:
      - .env
    working_dir: /home/node
    volumes:
      - ./:/home/node/scripts/:z
      - $HOME/.aws/:/home/node/.aws
      - /home/haniel/workspace/private/:/home/node/private/:z
      - /home/haniel/workspace/selina:/home/node/selina/:z
    command: "sh scripts/bash-scripts/dev.sh"
    user: ${UID}
    ports:
      - ${PORT_TO_EXPOSE}:${PORT_TO_LISTEN}
