version: '3'
services: 
  myapp:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: ${SERVICE_NAME}
    env_file:
      - .env
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app/:z
      - $HOME/.aws/:/home/node/.aws
    command: "sh bash-scripts/dev.sh"
    user: ${UID}
    ports:
      - ${PORT_TO_EXPOSE}:${PORT_TO_LISTEN}